repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.3.0 # You can use a newer version if available
    hooks:
    -   id: black
        args: [--line-length=127]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1 # You can use a newer version if available
    hooks:
    -   id: flake8
        args: [--max-line-length=127, --max-complexity=10, --select=E9,F63,F7,F82, --show-source, --statistics]
-   repo: https://github.com/PyCQA/ruff
    rev: 'v0.5.5'  # Replace with the latest version if desired
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.9'  # Replace with the latest version if desired
    hooks:
    -   id: bandit
        args: ['-r', 'katana/', '-s', 'B101'] # Example: run on katana dir, skip assert_used check
