repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.3.0 # You can use a newer version if available
    hooks:
    -   id: black
        args: [--line-length=127]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1 # You can use a newer version if available
    hooks:
    -   id: flake8
        args: [--max-line-length=127, --max-complexity=10, --select=E9,F63,F7,F82, --show-source, --statistics]
