#!/bin/bash

# This script deletes old and redundant branches from the repository.
# It was generated by Jules, the AI software engineer.

# Deleting jules_wip_* and jules/feature/* branches
git push origin --delete jules/feature/katana-bot-dialog-stub
git push origin --delete jules_wip_15321876708204576471
git push origin --delete jules_wip_7285569293321896304
git push origin --delete jules_wip_7653342708380051228
git push origin --delete jules_wip_7653342708380051228-1
git push origin --delete jules_wip_7833245367113789073
git push origin --delete jules_wip_7833245367113789073-1

# Deleting duplicate branches with suffixes like -1, -2, etc.
git push origin --delete dev-1
git push origin --delete dev-revive-bot-1
git push origin --delete feat/async-task-queue-1
git push origin --delete feat/auto-patch-self-heal-1
git push origin --delete feat/auto-patch-self-heal-1-1
git push origin --delete feat/auto-patch-self-heal-2
git push origin --delete feat/command-handling-improvements-1
git push origin --delete feat/katana-n8n-integration-1
git push origin --delete feat/slash-command-stub-1
git push origin --delete feat/streamlit-katana-integration-1
git push origin --delete feat/streamlit-katana-integration-2
git push origin --delete feat/telegram-command-parser-nlp-1
git push origin --delete feat/telegram-katana-bot-1
git push origin --delete feat/telegram-katana-bot-2
git push origin --delete feat/trace-bot-commands-1
git push origin --delete feature/advanced-nlp-integration-1
git push origin --delete feature/command-handling-enhancements-1
git push origin --delete feature/command-handling-enhancements-2
git push origin --delete feature/command-trace-visualizer-1
git push origin --delete feature/dao-agent-core-1
git push origin --delete feature/dao-agent-core-1-1
git push origin --delete feature/dao-agent-core-1-2
git push origin --delete feature/dialog-state-revision-1
git push origin --delete feature/katana-agent-router-integration-1
git push origin --delete feature/katana-agent-router-integration-2
git push origin --delete feature/katana-autosuggest-agent-1
git push origin --delete feature/katana-dynamic-monitoring-1
git push origin --delete feature/katana-dynamic-monitoring-2
git push origin --delete feature/katana-hydra-observer-1
git push origin --delete feature/katana-web-interface-1
git push origin --delete feature/standardize-logging-1
git push origin --delete feature/supabase-memory-core-1
git push origin --delete feature/supabase-memory-core-2
git push origin --delete feature/telegram-receiver-1
git push origin --delete fix/command-validation-and-log-test-1
git push origin --delete fix/command-validation-and-log-test-2
git push origin --delete fix/n8n-task-handler-1
git push origin --delete fix/n8n-task-handler-1-1
git push origin --delete infra/doppler-integration-1
git push origin --delete integration-mode-unleash-1
git push origin --delete integration-mode-unleash-2
git push origin --delete katana-initial-structure-1
git push origin --delete katana-initial-structure-2
git push origin --delete n8n-integration-1
git push origin --delete n8n-integration-1-1
git push origin --delete n8n-integration-1-2
git push origin --delete n8n-workflow-creation-1
git push origin --delete n8n-workflow-creation-2
git push origin --delete n8n-workflow-creation-3
git push origin --delete refactor-z-log-and_test-1
git push origin --delete setup/dev-infrastructure-1

# Deleting old feat/* branches superseded by feature/* branches
git push origin --delete feat/command-handling-improvements
git push origin --delete feat/advanced-nlp-integration
git push origin --delete feat/doppler-integration

echo "Cleanup script generated."