version: '3.8'

services:
  katana-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: katana-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Mount local directories for logs and data persistence
      - ./logs:/app/logs
      - ./user_data:/app/user_data
      - ./commands:/app/commands
    networks:
      - katana-net

  praetor-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praetor-agent
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - katana-bot
    networks:
      - katana-net

networks:
  katana-net:
    driver: bridge
