name: Katana CI

on:
  push:
    branches:
      - main
      - dev
      - feature/dependency-auto-healer
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Use a generic version or specify e.g., 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Katana Doctor
      run: python -m katana.cli doctor --auto-fix
    - name: Run tests
      run: python -m unittest discover -s tests -p 'test_*.py'
