name: Python Quality Checks

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Specify your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 black isort pyTelegramBotAPI
        # Add any other dependencies your bot needs to run tests or the bot itself if checks require it

    - name: Run quality checks
      run: |
        chmod +x run_checks.sh # Ensure script is executable
        ./run_checks.sh
