name: CI & Daily Sync

on:
  push:
    branches: [ main, setup/dev-infrastructure ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  build_and_test: # Renamed job for clarity
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Updated checkout action version

    - name: Set up Python
      uses: actions/setup-python@v5 # Updated setup-python action version
      with:
        python-version: '3.10' # Specified Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.lock # Install from lock file
        pip install pre-commit # Install pre-commit

    - name: Run pre-commit checks
      run: pre-commit run --all-files

    - name: Run script checks (includes pytest with coverage)
      run: |
        chmod +x ./scripts/run_checks.sh
        ./scripts/run_checks.sh

    - name: Upload stderr log on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: run-checks-stderr-log
        path: scripts/run_checks_stderr.log

  sync_supabase_data:
    name: Daily Supabase Sync
    runs-on: ubuntu-latest
    # Only run this job on scheduled triggers or pushes to main/dev branches,
    # not on every pull request build.
    if: github.event_name == 'schedule' || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/setup/dev-infrastructure'))
    needs: build_and_test # Ensure tests pass before syncing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Using requirements.txt for sync script

    - name: Run Supabase Sync Script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python scripts/sync_supabase.py
