name: CI

on:
  push:
    branches: [ main, setup/dev-infrastructure ] # Added the new branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Updated checkout action version

    - name: Set up Python
      uses: actions/setup-python@v5 # Updated setup-python action version
      with:
        python-version: '3.10' # Specified Python version

    - name: Setup Doppler CLI
      uses: dopplerhq/cli-action@v7
      with:
        token: ${{ secrets.DOPPLER_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.lock # Install from lock file
        pip install pre-commit # Install pre-commit

    - name: Run pre-commit checks
      run: pre-commit run --all-files

    - name: Run script checks (includes pytest with coverage)
      run: |
        chmod +x ./scripts/run_checks.sh
        doppler run -- ./scripts/run_checks.sh

    - name: Upload stderr log on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: run-checks-stderr-log
        path: scripts/run_checks_stderr.log
