name: Katana Self Diagnostic (daily)
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  selfcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r katana/requirements.txt
      - name: Run self-check
        run: python -m katana.self_check
